레이블 인코딩

In [1]:
#target에만 적용
from sklearn.preprocessing import LabelEncoder

items = ["청바지", "치마", "청바지", "원피스", "청바지", "치마", "치마", "청바지", "원피스"]

label_encoder = LabelEncoder()
label_encoder.fit(items)

LabelEncoder()

In [2]:
labels = label_encoder.transform(items)
labels

array([1, 2, 1, 0, 1, 2, 2, 1, 0])

In [3]:
#숫자를 다시 문자열로 디코딩
label_encoder.inverse_transform([2,1,0,0,1,2,0,0,1])

array(['치마', '청바지', '원피스', '원피스', '청바지', '치마', '원피스', '원피스', '청바지'],
      dtype='<U3')

In [4]:
#클래스 확인
label_encoder.classes_

array(['원피스', '청바지', '치마'], dtype='<U3')

원-핫인코딩(One-Hot Encoding)

In [5]:
from sklearn.preprocessing import OneHotEncoder
ohe_encoder = OneHotEncoder() # -> Feature(행렬로 표현)

In [6]:
#1차원 배열을 2차원 배열로 바꿔주기
# vector -> matrix
# N -> N X 1

import numpy as np

items_arr = np.array(items).reshape(-1,1)
items_arr

array([['청바지'],
       ['치마'],
       ['청바지'],
       ['원피스'],
       ['청바지'],
       ['치마'],
       ['치마'],
       ['청바지'],
       ['원피스']], dtype='<U3')

In [7]:
ohe_labels = ohe_encoder.fit_transform(items_arr)
ohe_labels

<9x3 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [8]:
print(ohe_labels)
# 희소 행렬 (sparse matrix)

  (0, 1)	1.0
  (1, 2)	1.0
  (2, 1)	1.0
  (3, 0)	1.0
  (4, 1)	1.0
  (5, 2)	1.0
  (6, 2)	1.0
  (7, 1)	1.0
  (8, 0)	1.0


In [9]:
ohe_labels.toarray()

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

Feature 스케일링

Min-Max Scaling(정규화)

In [10]:
import pandas as pd
movie_score = pd.DataFrame({
    "naver":[0, 2, 4, 6, 8],
    "netflix":[1, 2, 3, 4, 5]
})

movie_score

naver  netflix
0      0        1
1      2        2
2      4        3
3      6        4
4      8        5

In [12]:
from sklearn.preprocessing import MinMaxScaler
 
min_max_scaler = MinMaxScaler()

In [13]:
movie_score_scaled = min_max_scaler.fit_transform(movie_score)
movie_score_scaled

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [0.75, 0.75],
       [1.  , 1.  ]])

In [14]:
pd.DataFrame(movie_score_scaled, columns = ["Naver Scaled", "Netflix Scaled"])

Naver Scaled  Netflix Scaled
0          0.00            0.00
1          0.25            0.25
2          0.50            0.50
3          0.75            0.75
4          1.00            1.00

StandardScaling (표준화)
- 데이터를 원점 기준으로 정리  
- 평균 0, 표준편차 1 

In [15]:
data1 = np.array([100, 110, 120, 130, 140])
data2 = np.array([0,1,2,3,4])

In [18]:
data1.mean(), data1.std()

(120.0, 14.142135623730951)

In [19]:
data2.mean(), data2.std()

(2.0, 1.4142135623730951)

In [20]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()

In [21]:
data1_scaled = std_scaler.fit_transform(data1.reshape(-1,1))
data2_scaled = std_scaler.fit_transform(data2.reshape(-1,1))

In [22]:
print(data1_scaled)
print(data2_scaled)

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]
[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [23]:
data1_scaled.mean(), data1_scaled.std()

(0.0, 0.9999999999999999)

In [24]:
data2_scaled.mean(), data2_scaled.std()

(0.0, 0.9999999999999999)